# Generated by Django 2.0.5 on 2018-08-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shijing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='标题', max_length=100, verbose_name='标题')),
                ('chapter', models.CharField(default='', help_text='章名', max_length=100, verbose_name='章名')),
                ('section', models.CharField(default='', help_text='类名', max_length=100, verbose_name='类名')),
                ('content', models.TextField(default='', help_text='内容', verbose_name='内容')),
            ],
            options={
                'verbose_name': '诗经',
                'verbose_name_plural': '诗经',
                'db_table': 'shijing',
                'ordering': ['chapter'],
            },
        ),
    ]
